// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/navigation-ia/CurrentAdmin.tsx": () => import("../components/mockups/navigation-ia/CurrentAdmin.tsx"),
  "./components/mockups/navigation-ia/CurrentLMS.tsx": () => import("../components/mockups/navigation-ia/CurrentLMS.tsx"),
  "./components/mockups/navigation-ia/GroupedAdmin.tsx": () => import("../components/mockups/navigation-ia/GroupedAdmin.tsx"),
  "./components/mockups/navigation-ia/GroupedLMS.tsx": () => import("../components/mockups/navigation-ia/GroupedLMS.tsx")
};
